export const SET_CLIMATE_LOADING = 'SET_CLIMATE_LOADING';
export const SET_CLIMATE = 'SET_CLIMATE';
export const SET_PLAYLIST_LOADING = 'SET_PLAYLIST_LOADING';
export const SET_PLAYLIST = 'SET_PLAYLIST';
